<a href="https://colab.research.google.com/github/wayne4918/Big_Data/blob/bigdata/BigData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#빅데이터 정리

1. 열방향: 선택 -select()
2. 열방향: 계산 - mutate()
3. 행방향: 조건 - filter()
4. 행방향: 추가 - bind_rows()
5. 행방향: 정렬 - arrange()
6. 그룹 계산 - group_by()+summarise()
7. 열결합 - left_join()


###파이썬 자료형
1. 숫자형 (Nuberic)
 - Integer(정수)
 - Float(소수)
 - Complex(복소수)
2. Boolean (T or F)
3. Sequence Type
 - String(문자열)
 - list(리스트)
 - Tuple(튜플)
4. Set(집합)
5. Dictionary(딕셔너리)

In [ ]:
a = 10
type(a)

int

In [ ]:
b = 1.111
type(b)

float

In [ ]:
type("love y the way u r")

str

In [ ]:
type(["love","like"])

list

In [ ]:
type(("love","like"))

tuple

리스트 - 요소 변경가능

index -> []이런거 있는거

[0,1,2,3,4,5,]

[-6,-5,-4,-3,-2,-1]

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10]
print(a[len(a)-1])
print(a[-1])

print(a[:])
print(a[::2])
print(a[-1::-2])

print(a[len(a)-1::-1])
print(a[-1::-1])
print(a[::-1])

10
10
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 3, 5, 7, 9]
[10, 8, 6, 4, 2]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
c = [1,2,3,4,5]
c_square = [n**2 for n in c]
print(c_square)

[1, 4, 9, 16, 25]


In [ ]:
type({"one":1,"two":2,"three":3})

dict

In [ ]:
a = [2,3,4]
b = [2,7,3.5,"Hello"]
c = []

d = [2,[a,b]]
e = a+b

In [ ]:
print(d)
type(d)
y= b[1:4]
print(y)
print(e)
print(e[-1])
type(e[-2])

z = d[1][0][2]
print(z)

[2, [[2, 3, 4], [2, 7, 3.5, 'Hello']]]
[7, 3.5, 'Hello']
[2, 3, 4, 2, 7, 3.5, 'Hello']
Hello
4


In [ ]:
import pandas as pd
import numpy as np
X = np.array([[0,1,1],[1,0,1],[1,1,1],[0,1,1],[0,0,1]])
Y = np.array([1,0,1,0,1])
df = pd.DataFrame(X,columns=["1","2","3"])
df['Target']=Y

print(df)

   1  2  3  Target
0  0  1  1       1
1  1  0  1       0
2  1  1  1       1
3  0  1  1       0
4  0  0  1       1


In [ ]:
import numpy as np

# Rank 2 array
a = np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8],
              [9, 8, 7, 6, 5]])

print(a)
'''
[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
'''

# row 1 to 3 (not inclusive) and first 3 columns
b1 = a[1:3, :3]
print(b1)

# Last two rows and last two columns
b2 = a[-2:, -2:]
print(b2)

# row 1 onwards and column 2 onwards
b3 = a[1:, 2:]
print(b3)

# b3[0,2] is pointing to a[1,4]; modifying it will modify the original array
b3[0, 2] = 88
print(b3)

# Checking how the original array 'a' is modified
print(a)

# row 2 onwards and all columns
b4 = a[2:, :]
print(b4)
print(b4.shape)


[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]
[[4 5 6]
 [9 8 7]]
[[7 8]
 [6 5]]
[[6 7 8]
 [7 6 5]]
[[ 6  7 88]
 [ 7  6  5]]
[[ 1  2  3  4  5]
 [ 4  5  6  7 88]
 [ 9  8  7  6  5]]
[[9 8 7 6 5]]
(1, 5)


In [ ]:
import pandas as pd

# Pandas Series 생성
series = pd.Series([1, 2, 3, 4, 5])
print(series)

# 인덱스를 지정한 Pandas Series 생성
series = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'c'])
print(series)

# 위치 기반 인덱싱
print(series[2])          # 3
print(series.iloc[2])      # 3 - 위치에 따른 값 출력

# 레이블 기반 인덱싱
print(series['d'])         # 4
print(series.loc['d'])     # 4 - 레이블에 따른 값 출력

# 슬라이싱
print(series[2:])          # 슬라이싱, 시리즈 반환
print(series.iloc[2:])     # 위치에 기반한 슬라이싱, 시리즈 반환

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
c    5
dtype: int64
3
3
4
4
c    3
d    4
c    5
dtype: int64
c    3
d    4
c    5
dtype: int64


<ipython-input-16-e4a80876038e>:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series[2])          # 3


In [ ]:
import pandas as pd

# 날짜 범위 생성 (12개의 날짜)
dates1 = pd.date_range('20190525', periods=12)
print(dates1)

# Series 생성 및 날짜 인덱스 설정
series = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
series.index = dates1
print(series)


DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28',
               '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01',
               '2019-06-02', '2019-06-03', '2019-06-04', '2019-06-05'],
              dtype='datetime64[ns]', freq='D')
2019-05-25     1
2019-05-26     2
2019-05-27     3
2019-05-28     4
2019-05-29     5
2019-05-30     6
2019-05-31     7
2019-06-01     8
2019-06-02     9
2019-06-03    10
2019-06-04    11
2019-06-05    12
Freq: D, dtype: int64


In [ ]:
import pandas as pd
import numpy as np

# 랜덤 데이터를 가지는 DataFrame 생성
df = pd.DataFrame(np.random.randn(10, 4), columns=list('ABCD'))
print(df)

# DataFrame을 CSV 파일로 저장
df.to_csv('data.csv', index=False)


          A         B         C         D
0  0.504928 -1.044599 -0.627613  0.375485
1  1.456569  1.530619 -0.640408 -1.359487
2 -0.373992 -1.227641 -1.222415 -0.406982
3 -0.638624 -0.228940 -0.456072  0.239640
4 -2.265186  0.769735 -0.877103 -0.160772
5 -0.170301  1.149806  1.483201  0.316339
6  1.915772 -0.422619 -1.380887 -0.245290
7 -0.059690 -0.196578  0.613495 -0.025515
8  0.559441 -0.546745 -1.131045  0.470334
9  0.389284 -0.203566  1.028501  0.464145


In [ ]:
import pandas as pd

# CSV 파일 읽기
df = pd.read_csv('data.csv')

# 날짜 범위 생성 (10일간)
days = pd.date_range('20190525', periods=10)

# DataFrame의 인덱스를 날짜로 설정
df.index = days

# DataFrame 출력
print(df)

# 인덱스 출력
print(df.index)

# 값 출력
print(df.values)


                   A         B         C         D
2019-05-25  0.504928 -1.044599 -0.627613  0.375485
2019-05-26  1.456569  1.530619 -0.640408 -1.359487
2019-05-27 -0.373992 -1.227641 -1.222415 -0.406982
2019-05-28 -0.638624 -0.228940 -0.456072  0.239640
2019-05-29 -2.265186  0.769735 -0.877103 -0.160772
2019-05-30 -0.170301  1.149806  1.483201  0.316339
2019-05-31  1.915772 -0.422619 -1.380887 -0.245290
2019-06-01 -0.059690 -0.196578  0.613495 -0.025515
2019-06-02  0.559441 -0.546745 -1.131045  0.470334
2019-06-03  0.389284 -0.203566  1.028501  0.464145
DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28',
               '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01',
               '2019-06-02', '2019-06-03'],
              dtype='datetime64[ns]', freq='D')
[[ 0.50492789 -1.04459929 -0.62761284  0.37548511]
 [ 1.45656872  1.53061886 -0.64040799 -1.35948655]
 [-0.37399205 -1.22764081 -1.22241468 -0.40698204]
 [-0.63862381 -0.22893955 -0.45607242  0.23963972]
 

In [ ]:
# 통계 정보 출력
print(df.describe())

# 각 열의 평균 계산
print(df.mean(0))  # 0은 각 열에 대해 평균을 계산

# 각 행의 평균 계산
print(df.mean(1))  # 1은 각 행에 대해 평균을 계산

# 상위 5개 행 출력
print(df.head())

# 하위 5개 행 출력
print(df.tail())

# 특정 열 출력
print(df['A'])  # 열 'A' 출력
# 동일한 방법
print(df.A)

# 여러 열을 선택하여 출력
print(df[['A', 'B']])

# 슬라이싱을 통한 행 선택 (2번째부터 4번째까지)
print(df[2:4])

# iloc을 이용한 슬라이싱 (2번째부터 4번째까지)
print(df.iloc[2:4])

# A열과 B열의 값이 모두 0보다 큰 행을 선택
print(df[(df.A > 0) & (df.B > 0)])


               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean    0.131820  -0.042053  -0.321034  -0.033210
std     1.157047   0.909700   1.003615   0.560219
min    -2.265186  -1.227641  -1.380887  -1.359487
25%    -0.323069  -0.515714  -1.067559  -0.224160
50%     0.164797  -0.216253  -0.634010   0.107063
75%     0.545813   0.528157   0.346103   0.360699
max     1.915772   1.530619   1.483201   0.470334
A    0.131820
B   -0.042053
C   -0.321034
D   -0.033210
dtype: float64
2019-05-25   -0.197950
2019-05-26    0.246823
2019-05-27   -0.807757
2019-05-28   -0.270999
2019-05-29   -0.633331
2019-05-30    0.694761
2019-05-31   -0.033256
2019-06-01    0.082928
2019-06-02   -0.162004
2019-06-03    0.419591
Freq: D, dtype: float64
                   A         B         C         D
2019-05-25  0.504928 -1.044599 -0.627613  0.375485
2019-05-26  1.456569  1.530619 -0.640408 -1.359487
2019-05-27 -0.373992 -1.227641 -1.222415 -0.406982
2019-05-28 -0.638624 

In [ ]:
import pandas as pd

# 데이터 딕셔너리 생성
data = {
    'name': ['Janet', 'Nad', 'Timothy', 'June', 'Amy'],
    'year': [2012, 2012, 2013, 2014, 2014],
    'reports': [6, 13, 14, 1, 7]
}

# 데이터프레임 생성, 인덱스를 지정
df = pd.DataFrame(data, index=['Singapore', 'China', 'Japan', 'Sweden', 'Norway'])
print(df)

# Numpy 배열 생성 및 데이터프레임에 새로운 열 추가
import numpy as np
schools = np.array(["Cambridge", "Oxford", "Oxford", "Cambridge", "Oxford"])
df["school"] = schools
print(df)

# 인덱스를 기준으로 행 제거
print(df.drop(['China', 'Japan']))

# 특정 열의 값 조건을 기준으로 행 제거
print(df[df.name != 'Nad'])

# 열 제거
print(df.drop('reports', axis=1))


              name  year  reports
Singapore    Janet  2012        6
China          Nad  2012       13
Japan      Timothy  2013       14
Sweden        June  2014        1
Norway         Amy  2014        7
              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
China          Nad  2012       13     Oxford
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford
            name  year  reports     school
Singapore  Janet  2012        6  Cambridge
Sweden      June  2014        1  Cambridge
Norway       Amy  2014        7     Oxford
              name  year  reports     school
Singapore    Janet  2012        6  Cambridge
Japan      Timothy  2013       14     Oxford
Sweden        June  2014        1  Cambridge
Norway         Amy  2014        7     Oxford
              name  year     school
Singapore    Janet  2012  Cambridge
China          Nad  2012     Oxford
Japan      Timothy  2

In [ ]:
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame(
    {
        "Gender": ['Male', 'Male', 'Female', 'Female', 'Female'],
        "Team": [1, 2, 3, 3, 1]
    }
)
print(df)

# 성별에 따른 팀 분포를 표시
print("Displaying the distribution of genders in each team")
print(pd.crosstab(df.Gender, df.Team))

# 팀별 성별 분포를 표시
print(pd.crosstab(df.Team, df.Gender))


   Gender  Team
0    Male     1
1    Male     2
2  Female     3
3  Female     3
4  Female     1
Displaying the distribution of genders in each team
Team    1  2  3
Gender         
Female  1  0  2
Male    1  1  0
Gender  Female  Male
Team                
1            1     1
2            0     1
3            2     0
